### ISSUE TITLE
New release asset upload 'Deprecation' message in log output

### ISSUE THREAD

**Issue by nialov** [softprops/action-gh-release#129]
# Info

`softprops/action-gh-release@v1` failed with a 'Deprecation' error.

See gist link for the error message:

https://gist.github.com/nialov/e151ed3511bc55de3dae2bacb91b0ddb

# Background

My workflow additionally uses:

~~~yaml
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6

      - name: Zip
        uses: papeloto/action-zip@v1
~~~

**Comment by hipersayanX** [comment]
Same

**Comment by softprops** [comment]
This probably came with a release updates you should be able to use @0.5.1 in the mean time

https://github.com/softprops/action-gh-release/blob/master/CHANGELOG.md#015

I’ll take a look tonight

**Comment by hipersayanX** [comment]
@softprops 

I tried using 0.5.1 as you said, as

```
uses: softprops/action-gh-release@0.5.1
```

And it give me the following error

```
Error: Unable to resolve action `softprops/action-gh-release@0.5.1`, unable to find version `0.5.1`
```

**Comment by nialov** [comment]
Seems like my issue was of my own making, was forcing a release on top of an already existing release (duplicate tags) or something similarly dumb. The deprecation is seemingly only a warning (appears on successful runs also) but it does make it confusing on what the actual issue is.

The below 'standard' config works for me:

~~~yaml
- name: Release
  uses: softprops/action-gh-release@v1
~~~

**Comment by hipersayanX** [comment]
Fixed for me using @v0.1.6.

**Comment by linonetwo** [comment]
Same on me https://github.com/tiddly-gittly/TiddlyGit-Desktop/runs/3174941044?check_suite_focus=true

```
⬆️ Uploading RELEASES...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
⬆️ Uploading TiddlyGit-0.4.1-a19-full.nupkg...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
⬆️ Uploading TiddlyGit-0.4.1-a19-Windows-arm64-setup.exe...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
⬆️ Uploading RELEASES...
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
⬆️ Uploading TiddlyGit-0.4.1-a19-full.nupkg...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
⬆️ Uploading TiddlyGit-0.4.1-a19-Windows-x64-setup.exe...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:436958)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:52043
    at Generator.next (<anonymous>)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50565
    at new Promise (<anonymous>)
    at i (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:50313)
    at Object.t.upload (D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:51907)
    at D:\a\_actions\softprops\action-gh-release\v1\dist\index.js:1:44485 {
  name: 'Deprecation'
}
Error: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
```

I think in this time, I am using @v0.1.6.

**Comment by softprops** [comment]
I can reproduce the warnings but not yet the error. I have a test run [here](https://github.com/softprops/action-gh-releases-test/runs/3178465743) (sample run output below)



```
Run softprops/action-gh-release@v0.1.7
⬆️ Uploading a.txt...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:437047
⬆️ Uploading b.txt...
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:436958)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:52043
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:50565
    at new Promise (<anonymous>)
    at i (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:50313)
    at Object.t.upload (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:51907)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:44485 {
  name: 'Deprecation'
}
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:436958)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:52043
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:50565
    at new Promise (<anonymous>)
    at i (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:50313)
    at Object.t.upload (/home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:51907)
    at /home/runner/work/_actions/softprops/action-gh-release/v0.1.7/dist/index.js:1:44485 {
  name: 'Deprecation'
}
🎉 Release ready at https://github.com/softprops/action-gh-releases-test/releases/tag/v0.1.2
```

a warning is an indicator that I need to upgrade something but should not fail your build. which makes this a bit less urgent for me. something that I can perhaps get to this weekend

@linonetwo it looks like in your case the real error  isn't related to the warnings but the error that followed

> Error: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}

This indicates that you may have already uploaded a release asset of the same name causing a conflict which I believe is failing your build. I'd need to see your workflow setup to get a better sense for how the release asset might have been previously uploaded. That said, upserting (updating or creating) assets is something I'd love to add support for in this gh action

**Comment by linonetwo** [comment]
Thank you @softprops , my workflow is https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/c0c979a1fb01648cdc1df57a033485bbe57d7a20/.github/workflows/release.yml#L151-L175

It is not easy to know which file is in conflict, hope there can be a log about file name.

**Comment by softprops** [comment]
Would it be possible to add an ls directory listing in the step prior to debug?

**Comment by linonetwo** [comment]
Seems two windows build make same `TiddlyGit-0.4.1-a21-full.nupkg` file, and it causes the error, previously this will just silently overwritten.

**Comment by Loyalsoldier** [comment]
Same problem here:

https://github.com/Loyalsoldier/v2ray-rules-dat/runs/3176493282?check_suite_focus=true
https://github.com/Loyalsoldier/v2ray-rules-dat/runs/3186538209?check_suite_focus=true

**Comment by linonetwo** [comment]
I limit the uploaded file to only `**/*.exe`, then it works fine. Just can't upload anything that may have same name. And rerun-all-jobs is not working anymore, because the re-upload will fail.

**Comment by kiview** [comment]
I see the same problem in our build with regards to duplicate uploads. However, AFAIK duplicate uploads worked for us before, so I assume there is some regression that changed this behavior?

**Comment by softprops** [comment]
This think this regressed in the fix here https://github.com/softprops/action-gh-release/pull/97

**Comment by softprops** [comment]
I’m going to open a separate issue to not confuse this with the deprecation warnings

**Comment by softprops** [comment]
I’m going to update the title of this issue. Releases don’t fail with just the gh api warnings

**Comment by hipersayanX** [comment]
Seem many people are talking about using this action for uploading duplicated files, and I forgot to say but this is my case, I've configured my workflow to upload a new set of assets with every new commit so users can test it, the assets are disposable so they aren't versioned at all, and are always uploaded to the same tag/release.
From what you said before:

@softprops

>This indicates that you may have already uploaded a release asset of the same name causing a conflict which I believe is failing your build.

You should consider allow overwriting the assets.

**Comment by Loyalsoldier** [comment]
Use the v0.1.8 and failed again:

```
👩‍🏭 Creating new GitHub release for tag 202108080610...
⬆️ Uploading apple-cn.txt...
⬆️ Uploading direct-list.txt...
⬆️ Uploading direct-tld-list.txt...
⬆️ Uploading geoip.dat...
⬆️ Uploading geoip.dat.sha256sum...
⬆️ Uploading geosite.dat...
⬆️ Uploading geosite.dat.sha256sum...
⬆️ Uploading gfw.txt...
⬆️ Uploading google-cn.txt...
⬆️ Uploading greatfire.txt...
⬆️ Uploading proxy-list.txt...
⬆️ Uploading proxy-tld-list.txt...
⬆️ Uploading reject-list.txt...
⬆️ Uploading reject-tld-list.txt...
⬆️ Uploading rules.zip...
⬆️ Uploading rules.zip.sha256sum...
⬆️ Uploading win-extra.txt...
⬆️ Uploading win-spy.txt...
⬆️ Uploading win-update.txt...
Error: Failed to upload release asset ${name}. recieved status code ${resp.status}
${json.message}
${json.errors}
```

https://github.com/Loyalsoldier/v2ray-rules-dat/runs/3272404245?check_suite_focus=true

**Comment by Loyalsoldier** [comment]
Use v0.1.10 and failed again:

```
👩‍🏭 Creating new GitHub release for tag 202108081632...
⚠️ GitHub release failed with status: 404, retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag 202108081632...
⚠️ GitHub release failed with status: 422, retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag 202108081632...
⚠️ GitHub release failed with status: 422, retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```
