### ISSUE TITLE
Unhandled HttpError and fail silently

### ISSUE THREAD

**Issue by ouuan** [softprops/action-gh-release#43]
See the "Release on Mac" step of the "macos-latest Qt 5.12.7" job [here](https://github.com/cpeditor/cp-editor/runs/469720568). It failed silently.

The log:

```
Run softprops/action-gh-release@v1
  with:
    draft: true
    files: build/CP_Editor-6.0.2-x64.dmg
    name: CP Editor 6.0.2
  env:
    CMAKE_VERSION: 3.16.4
    NINJA_VERSION: 1.10.0
    BUILD_TYPE: Release
    CCACHE_VERSION: 3.7.7
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.6/x64
    Qt5_Dir: /Users/runner/runners/2.165.2/work/cp-editor/Qt/5.12.7/clang_64
    GITHUB_TOKEN: ***
👩‍🏭 Creating new GitHub release for tag 6.0.2...
⬆️ Uploading CP_Editor-6.0.2-x64.dmg...
🎉 Release ready at https://github.com/cpeditor/cp-editor/releases/tag/untagged-75575abc284ad6a2f272
(node:2738) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /Users/runner/runners/2.165.2/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected behavior: this step should fail after this error.

**Comment by Loyalsoldier** [comment]
Same issue.

```
👩‍🏭 Creating new GitHub release for tag 202003010505...
⬆️ Uploading direct-excluse-list...
⬆️ Uploading direct-list...
⬆️ Uploading geoip.dat...
⬆️ Uploading geoip.dat.sha256sum...
⬆️ Uploading geosite.dat...
⬆️ Uploading geosite.dat.sha256sum...
⬆️ Uploading proxy-excluse-list...
⬆️ Uploading proxy-list...
⬆️ Uploading reject-excluse-list...
⬆️ Uploading reject-list...
🎉 Release ready at https://github.com/Loyalsoldier/v2ray-rules-dat/releases/tag/202003010505
(node:5352) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5352) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

10 files exist, but 2 of them failed while 8 of them are uploaded successfully.

**Comment by softprops** [comment]
this is now fixed.
