### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Error saving asset

### ISSUE THREAD

**Issue by hayd** [softprops/action-gh-release#46]
It looks like the file exists but the upload fails (and is not retried):

```
Run softprops/action-gh-release@v1
  with:
    files: amz-deno.gz
  deno-lambda-layer.zip
  deno-lambda-example.zip
  
    draft: true
  env:
    GITHUB_TOKEN: ***
⬆️ Uploading amz-deno.gz...
⬆️ Uploading deno-lambda-layer.zip...
⬆️ Uploading deno-lambda-example.zip...
🎉 Release ready at https://github.com/hayd/deno-lambda/releases/tag/0.35.0
(node:4725) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This is the first time I've seen this, previously it has been working.

**Comment by Loyalsoldier** [comment]
Same issue.

```
👩‍🏭 Creating new GitHub release for tag 202003010505...
⬆️ Uploading direct-excluse-list...
⬆️ Uploading direct-list...
⬆️ Uploading geoip.dat...
⬆️ Uploading geoip.dat.sha256sum...
⬆️ Uploading geosite.dat...
⬆️ Uploading geosite.dat.sha256sum...
⬆️ Uploading proxy-excluse-list...
⬆️ Uploading proxy-list...
⬆️ Uploading reject-excluse-list...
⬆️ Uploading reject-list...
🎉 Release ready at https://github.com/Loyalsoldier/v2ray-rules-dat/releases/tag/202003010505
(node:5352) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5352) UnhandledPromiseRejectionWarning: HttpError: Error saving asset
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

2 files failed while 10 of them are okay.

**Comment by Loyalsoldier** [comment]
Duplicate #43
