### ISSUE TITLE
Allow removal for old releases

### ISSUE THREAD

**Issue by matklad** [softprops/action-gh-release#47]
Hi! I am looking to setup *nightly* releases for rust-analyzer, and for that I want to publish a github release every night under the same tag. IE, I want the tag itself to move. Looks like at the moment actions-gh-release silently fails in this case:

```

Release
1s
(node:2749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Run softprops/action-gh-release@v1
⬆️ Uploading rust-analyzer-linux...
⬆️ Uploading rust-analyzer-windows.exe...
⬆️ Uploading rust-analyzer-mac...
⬆️ Uploading rust-analyzer.vsix...
🎉 Release ready at https://github.com/matklad/rust-analyzer/releases/tag/2020-03-04
(node:2749) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2749) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2749) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2749) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

Failing by default is probably the right behavior, but it would be cool if the action had an `overwrite: boolean` flag to control this behavior

**Comment by ame-yu** [comment]
I have same problem.
In my case i want hava only one release for my repository which called `latest`

**Comment by BotellaA** [comment]
@softprops What do you think about this feature? I would love to have an overwrite option!

**Comment by ppaulweber** [comment]
@matklad I've had a similar problem and already suggested a possible solution at #45 in order to represent an `nightly` release behavior as well. Furthermore, have a look at the issues #42 and #43 which have a quite similar problem.

**Comment by greggameplayer** [comment]
For me it would also be good to have an overwrite feature

**Comment by proddy** [comment]
me too

**Comment by brianpham** [comment]
I would like this too. +1

We are currently using the same tag for releases and as a workaround, we need to delete the tags before it gets push again.

**Comment by JustinGrote** [comment]
I would like behavior similar to release drafter where on every main commit I can have a draft release added that updates with the latest release notes, and when I publish the release it triggers my github action to deploy. 

Release drafter doesn't let me specify my own release notes however which is why I came here. As a workaround I am deleting the release prior to publishing.

https://github.com/marketplace/actions/release-drafter

**Comment by softprops** [comment]
from the error in the description it seems this is more related to assets than the release itself. upserting assets is now the default which should fix this issue
